/*
 *  Copyright (c) 2026 A.V.U.T. Project.
 *  Licensed under the MIT License. See LICENSE.md in the project root for license information.
 */

import crypto from "crypto";

const ALGORITHM = "aes-256-gcm";
const CIPHERTEXT_ENCODING = "base64";

/**
 * Encrypt the given text using AES-256-GCM with the provided secret. The secret must be 32 characters long (256 bits) for AES-256. The function generates a random initialization vector (IV) for each encryption operation, which is recommended for security. The IV, encrypted data, and authentication tag are concatenated and returned as a Base64 string.
 * @param text The plaintext to encrypt.
 * @param secret The encryption secret (must be 32 characters long).
 * @returns The encrypted value as a Base64 string.
 * @throws Error if the secret is invalid.
 */
export function encryptValue(text: string, secret: string): string {
    if (!secret || secret.length !== 32) {
        throw new Error(
            "Invalid encryption secret. Must be 32 characters long.",
        );
    }

    // Generate a random 96-bit (12-byte) initialization vector. This is the recommended size for GCM mode.
    const iv = crypto.randomBytes(12);
    const cipher = crypto.createCipheriv(ALGORITHM, secret, iv);

    const encrypted = Buffer.concat([
        cipher.update(text, "utf8"),
        cipher.final(),
    ]);

    // Retrieve the authentication tag generated by GCM mode, which is used to verify the integrity of the ciphertext during decryption.
    const authTag = cipher.getAuthTag();

    // Concatenate all parts and return as Base64
    return Buffer.concat([iv, encrypted, authTag]).toString(
        CIPHERTEXT_ENCODING,
    );
}

/**
 * Decrypt the given ciphertext using AES-256-GCM with the provided secret. The function expects the input to be a Base64 string that contains the concatenated initialization vector (IV), encrypted data, and authentication tag. It extracts these components, initializes the decipher with the IV and secret, and verifies the authentication tag before returning the decrypted plaintext.
 * @param ciphertext The encrypted value as a Base64 string.
 * @param secret The decryption secret (must be the same as used for encryption).
 * @returns The decrypted plaintext.
 * @throws Error if the secret is invalid or if decryption fails (e.g., due to authentication failure).
 */
export function decryptValue(ciphertext: string, secret: string): string {
    if (!secret || secret.length !== 32) {
        throw new Error(
            "Invalid encryption secret. Must be 32 characters long.",
        );
    }

    const data = Buffer.from(ciphertext, CIPHERTEXT_ENCODING);

    // Extract the initialization vector (IV), encrypted data, and authentication tag from the input
    const iv = data.subarray(0, 12); // First 12 bytes for IV
    const authTag = data.subarray(data.length - 16); // Last 16 bytes for auth tag
    const encrypted = data.subarray(12, data.length - 16); // Middle part is the encrypted text

    const decipher = crypto.createDecipheriv(ALGORITHM, secret, iv);
    decipher.setAuthTag(authTag);

    const decrypted = Buffer.concat([
        decipher.update(encrypted),
        decipher.final(),
    ]);

    return decrypted.toString("utf8");
}

/**
 * Encrypt the given text for storage in the database. This function retrieves the encryption secret from the environment variable `DB_ENCRYPTION_SECRET` and uses it to encrypt the text. The encrypted value is returned as a Base64 string. If the environment variable is not set, an error is thrown.
 * @param text The plaintext to encrypt.
 * @returns The encrypted value as a Base64 string.
 * @throws Error if the encryption secret is not set or invalid.
 */
export function encryptDBValue(text: string): string {
    const secret = process.env.DB_ENCRYPTION_SECRET;
    if (!secret) {
        throw new Error(
            "DB_ENCRYPTION_SECRET environment variable is not set.",
        );
    }
    return encryptValue(text, secret);
}

/**
 * Decrypt the given ciphertext retrieved from the database. This function retrieves the decryption secret from the environment variable `DB_ENCRYPTION_SECRET` and uses it to decrypt the ciphertext. The input is expected to be a Base64 string that contains the concatenated initialization vector (IV), encrypted data, and authentication tag. The decrypted plaintext is returned as a string. If the environment variable is not set or if decryption fails, an error is thrown.
 * @param ciphertext The encrypted value as a Base64 string.
 * @returns The decrypted plaintext.
 * @throws Error if the decryption secret is not set, invalid, or if decryption fails.
 */
export function decryptDBValue(ciphertext: string): string {
    const secret = process.env.DB_ENCRYPTION_SECRET;
    if (!secret) {
        throw new Error(
            "DB_ENCRYPTION_SECRET environment variable is not set.",
        );
    }
    return decryptValue(ciphertext, secret);
}
