/*
 *  Copyright (c) 2025 A.V.U.T. Project.
 *  Licensed under the MIT License. See LICENSE.md in the project root for license information.
 */

import {
    ArchiveIcon,
    ArchiveRestoreIcon,
    ArrowDownUpIcon,
    ArrowRightLeftIcon,
    ArrowLeftIcon,
    BellIcon,
    BookOpenIcon,
    CheckCheckIcon,
    CheckIcon,
    ChevronRightIcon,
    CircleCheckIcon,
    CircleIcon,
    CircleUserRoundIcon,
    CircleXIcon,
    CopyIcon,
    FunnelIcon,
    FlaskConicalIcon,
    HistoryIcon,
    InfoIcon,
    KeyRoundIcon,
    LayoutDashboardIcon,
    LinkIcon,
    Link2OffIcon,
    MoreVerticalIcon,
    PencilIcon,
    PencilRulerIcon,
    PlusIcon,
    ScanEyeIcon,
    SendIcon,
    SettingsIcon,
    ShieldHalfIcon,
    SlashIcon,
    TrashIcon,
    TriangleAlertIcon,
    UsersIcon,
    XIcon,
    BookUpIcon,
    BookXIcon,
    MoveIcon,
    CircleSlashedIcon,
    MessageSquarePlusIcon,
} from "lucide-react";

export {
    InfoIcon as AlertInfoIcon,
    CircleCheckIcon as AlertSuccessIcon,
    TriangleAlertIcon as AlertWarningIcon,
    CircleXIcon as AlertErrorIcon,
    FlaskConicalIcon as AlertMockupIcon,
    BookOpenIcon as DocumentationIcon,
    MoreVerticalIcon as DropdownMenuTriggerIcon,
    ChevronRightIcon as ItemLinkActionIcon,
    BellIcon as NotificationsIcon,
    FunnelIcon as FilterColumnValuesIcon,
    LayoutDashboardIcon as OrgDashboardIcon,
    ArrowLeftIcon as ToParentPageIcon,
    ArrowDownUpIcon as ReorderIcon,

    // Object Icons
    ArchiveIcon as ArchiveObjectIcon,
    PlusIcon as CreateNewIcon,
    TrashIcon as DeleteObjectIcon,
    CopyIcon as DuplicateObjectIcon,
    PencilIcon as EditObjectIcon,
    ArchiveRestoreIcon as RestoreObjectIcon,

    // Personal Icons
    LayoutDashboardIcon as PersonalDashboardIcon,
    CircleUserRoundIcon as PersonalProfileIcon,
    KeyRoundIcon as PersonalD4HAccessTokensIcon,
    SettingsIcon as PersonalSettingsIcon,
    UsersIcon as PersonnelIcon,
    PencilRulerIcon as SessionRecordIcon,
    ScanEyeIcon as SessionReviewIcon,
    SettingsIcon as SettingsIcon,
    CheckIcon as SkillCheckCompetentIcon,
    CheckCheckIcon as SkillCheckHighlyConfidentIcon,
    CircleIcon as SkillCheckNotAssessedIcon,
    XIcon as SkillCheckNotCompetentIcon,
    SlashIcon as SkillCheckNotTaughtIcon,
    ArrowRightLeftIcon as SwitchOrganizationIcon,
    ShieldHalfIcon as TeamsIcon,
    SendIcon as InvitationsIcon,
};

export const ObjectIcons = {
    Archive: ArchiveIcon,
    Create: PlusIcon,
    Delete: TrashIcon,
    Duplicate: CopyIcon,
    Edit: PencilIcon,
    History: HistoryIcon,
    Link: LinkIcon,
    Move: MoveIcon,
    Publish: BookUpIcon,
    Restore: ArchiveRestoreIcon,
    Unlink: Link2OffIcon,
    Unpublish: BookXIcon,
};

export const SkillsIcons = {
    AddNotes: MessageSquarePlusIcon,
    Competent: CheckIcon,
    HighlyConfident: CheckCheckIcon,
    NotAssessed: CircleIcon,
    NotCompetent: XIcon,
    NotTaught: CircleSlashedIcon,
};
